// <auto-generated />
namespace MvcBootstrap.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update_RowVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_RowVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201309231455545_Update_RowVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
